name: Build
# Events
on:
  # Push to master
  push:
    branches: 
      - 'master'
  # Manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Tipo de VM
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3
      # Aqui instalamos o node
      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          # Este input é opcional, mas nesse caso a versão não é definida
          # outra opção é passar `latest` para ter a versão mais recente
          node-version: 18
      # Aqui instalamos as dependências do nosso projeto.
      # Utilizamos `npm ci` que é uma versão própria do `npm install` nativa ao npm,
      # esta usa sempre o package-lock e não atualiza nada indevidamente.
      - name: Install project dependencies
        run: npm ci
      - name: Build project
        run: npm run build
